### ISSUE TITLE
Re-style the login screen

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#31]
Once issue #30 is complete. Insert the new image into top of the login page.

DoD: the new image is on the Login page

**Comment by siuanm** [comment]
Hi Katrina-

I was not planning two separate images.

My understanding is that we need to have the CVOEO logo on the landing page
with the MoMM logo. Will have to figure out the best way to do that, as it
could look really busy and garish. (Kinda bummed it needs to be there from
an aesthetic perspective, but understand why it does!)

I was not planning to create an image for the top app bar on the dashboard.
But, I could look into it. So far, I have been adhering pretty strictly to
material design standards for the whole dashboard, hoping that makes it
easier to build and be cross platform. So, I was just incorporating the
material design system regular top app bar component for that page. I think
if the app gets more functionality down the road, this will also be good
for adding a hamburger or other navigation options, without having to do
much redesign. I could play around with color and typography for that
component if you think its a bit lackluster?  Let me know what you think.

Siuan

Siuan McGahan

www.siuan.com
+1 407 308 1209

**Comment by siuanm** [comment]
There are two images in the CVOEO team drive images folder- 1. CVOEO logo and 2. Financial Futures Program graphic. Do I need to incorporate both on the landing page (please, please, please say 'no') or can I just get away with the CVOEO logo?

**Comment by siuanm** [comment]
Here is the documentation on the material design guidelines I have been using for the app bar: https://material.io/design/components/app-bars-top.html#  So far I haven't included any icons for further navigation (like hamburger, overflow, search,, etc) but I can see them being needed if we add any more functionality, even a profile to manage, etc... 

I put some toolbar ideas on usabilityhub for you to take a look at: https://app.usabilityhub.com/do/222e6694300f/95c8  The blue one is the material design standard. The others are easy on my end, but I don't have to write the code. So someone from the development end would need to chime in on that.

**Comment by doub1ejack** [comment]
@siuanm Which "header image" should be added to the login screen.  Is this the same "MoMM" graphic that @jbpayne has added to the top of the Dashboard?  Would you like it in the same place?

![image](https://user-images.githubusercontent.com/1809882/51054933-5a984e80-15ac-11e9-95ac-e265b83f955e.png)

**Comment by jbpayne** [comment]
Is there a larger version of that graphic available?

**Comment by doub1ejack** [comment]
@jbpayne This image (LandingPageImage.jpg) is in the team drive.  Is it too small?  

<img src="https://lh4.googleusercontent.com/_3o99a-15kzdUpKPikq59Oj66BzjmiwLLRjPKJY0o8RqFTyH1nquV2f6_vdp3oPEcsMsYEGACqhOCA=w1439-h766">

I also see MoneyBrain.jpg in [the cvoeo folder](https://drive.google.com/drive/u/2/search?q=type:image%20parent:1KdC_iNceHcSPv8EPmJReyZeforcQULnO) and some versions of the Financial Futures logo in the drive.  You could style those accordingly, or ask Siuan for a larger version of LandingPageImage.jpg

**Comment by doub1ejack** [comment]
Ok, so currently this issue is all about restyling the login screen to go from it's current appearance to Siuan's newer version:

| old | new |
|---|---|
| <img src="https://lh3.googleusercontent.com/eh3R7RLxQedE43Vsgi4bRFUyAEKxCqjWD1eWA4iAN8UyPPaC1hbSJyKjddxLvguX05myUQbR3BdKtlUGczsijMwfLR3yaaqv2f2v1XYdKe4OOA7iSOyK9AQ3aFQ-ajVmz-Qmf35PlO8=w433-h767-no" width="200"> | <img src="https://user-images.githubusercontent.com/38860905/51055045-ad720600-15ac-11e9-9760-8881b372ffc9.png" width=200>|

Resources needed should be on [the Team Drive](https://drive.google.com/drive/u/2/search?q=type:image%20parent:1KdC_iNceHcSPv8EPmJReyZeforcQULnO), including 

* moneyOnMyMind.png
   <img src="https://lh6.googleusercontent.com/XjK9-ZScUqNeCe3eWEQdHcFxZ5ZfHRKFcxDRgunBiHf85d-3JkBYpGlRiQPZBvJgVtLeD7UnnxZQNg=w1439-h766" width=150>
* LandingPageImage.jpg
   <img src="https://camo.githubusercontent.com/6e82168a8d0b27e916ad4c539cfb4af1c1beab06/68747470733a2f2f6c68342e676f6f676c6575736572636f6e74656e742e636f6d2f5f336f3939612d31356b7a6455704b50696b7135394f6a3636427a6a6d69774c4c526a504b4a59306f38527146547948316e7175563266365f766470336f504563734d73594547414371684f43413d77313433392d68373636" width=150>
* [style guide](https://drive.google.com/open?id=1YVusLfBxnMZOL84CU9dhyH0PpHFqH6ph) with color codes

**Comment by jbpayne** [comment]
Yeah, the money brain image is definitely the limiting factor, so hopefully
Kate can get us a larger version.  If not, that's ok.  Siuan did a great
job with what she had available!

**Comment by siuanm** [comment]
The image we got from Kate is extremely low res. I just found another version of it on someone else's website that is higher resolution. I will modify it to match our design and we can see if it works. Will get that to you asap.

**Comment by siuanm** [comment]
![hires-money-brain](https://user-images.githubusercontent.com/38860905/51077649-89c7c200-1677-11e9-8a8e-293fa20c63a3.png)
I put a copy of this on drive in design materials/assets. This is much higher resolution than the original image. The background color is slightly different than the original image, so everywhere that was #04A0C6 should now be #01a0c7. I will update the color palette info.

**Comment by kmeyersvt** [comment]
Nice, thank you!

**Comment by jbpayne** [comment]
See https://github.com/codeforbtv/cvoeo-app/pull/52
